### ISSUE TITLE
Wait until Unity and scene are fully initialized before connecting to relay

### ISSUE THREAD

**Issue by parseccentric** [gelic-idealab/komodo-unity#29]
See https://gitlab.engr.illinois.edu/dev-studio/komodo/komodo_unity/-/issues/105 .

**Comment by davtamay** [comment]
This ended up being due to loading times of clients, if it took longer than 5 seconds the connection will be dropped. @wallacerob Did a fix on increasing default time to 30.  

Option      Default valueDescription
pingTimeout 5000    how many ms without a pong packet to consider the connection closed

"theory is that if we increase this from 5 seconds to like 30 it might fix the current issue"

**Comment by wallacerob** [comment]
yes, this is hotfixed with the relay hack described by @davtamay . Real fix will be waiting to initialize socket connection until after we are finished doing our local Unity setup.

**Comment by wallacerob** [comment]
we should probably change this issue to "Wait until Unity and scene are fully initialized before connecting to relay" or some such.

**Comment by parseccentric** [comment]
Previously entitled "State catch-up and network relay sync possibly breaks down after multi-client bump"

**Comment by wallacerob** [comment]
https://github.com/gelic-idealab/komodo-unity/commit/0caa45992e7c5d975be3f78a498106105340b131
