### ISSUE TITLE
Drawing memory leak and/or update problem

### ISSUE THREAD

**Issue by parseccentric** [gelic-idealab/komodo-unity#46]
Quest Oculus browser x 2
Rift S FireFox with Oculus Runtime
Desktop spectator (Brave?)

Runtime memory access out-of-bounds error happens in as little as 40 strokes when someone has entered in a session, or much fewer if someone is entering a session while someone is drawing. This is even if the session has no models. 

Quest crashes mostly, but desktop spectator views can also crash. 

Related errors:
```Could not allocate memory: System out of memory!
Trying to allocate: 619511808B with 16 alignment. MemoryLabel: DynamicArray
Allocation happened at: Line:70 in
``` 
-- printed in desktop spectator console. 

Possible related issues: 
Too many update calls

**Comment by davtamay** [comment]
This issue is fixed in hotfix 5d4275342f504dc633d4247e7268726754e2e6b6  , The issue was related to a parenting problem when creating strokes for those receiving draw calls for strokes. I separated logic from ClientSpawnManager.cs to DrawingInstanceManager.cs to assist in building the redo/undo system.
